#! /bin/sh

# --- Monitors ---
xrandr --output HDMI-0 --primary
xrandr --output DP-0 --mode 1280x1024 --rate 75.02
xrandr --output HDMI-0 --left-of DP-0

# --- Autostart Daemons ---
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x feh > /dev/null || ~/.fehbg &
pgrep -x polybar > /dev/null || polybar &

# --- Keyboard Layout ---
setxkbmap -option grp:alt_shift_toggle us,ru &

# --- Catppuccin Theme ---
xsetroot -cursor_name "Catppuccin Mocha Dark"
[[ -f ~/.config/.Xresources ]] && xrdb -merge ~/.config/.Xresources

# --- Initial Scripts ---
~/.config/bspwm/update-notifier
pass git pull

telegram-desktop

# --- bspc settings ---
bspc monitor -d 一 二 三 四 五 六 七 八 九 

bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#89b4fa"

bspc rule -a TelegramDesktop desktop='Desktop' state=floating follow=on rectangle=870x625+2143+183
bspc rule -a firefox:Navigator desktop='^2' follow=on
bspc rule -a firefox:Toolkit:"Picture-in-Picture" state=floating
bspc rule -a discord:discord desktop='Desktop' state=floating follow=on
bspc rule -a btop state=floating center=on follow=on rectangle=1142x773+389+153
bspc rule -a floating_kitty state=floating center=on follow=on rectangle=800x500+514+323
bspc rule -a obsidian desktop='^3'
bspc rule -a Steam:Steam desktop='^5' follow=on
