#!/bin/sh

music_dir="$MUSIC_DIR"
preview_dir="$XDG_CONFIG_HOME/ncmpcpp/previews"
filename="$(mpc --format "$music_dir"/%file% current)"
preview_name="$preview_dir/$(mpc --format %album% current | base64).png"

[ -e "$preview_name" ] || ffmpeg -y -i "$filename" -an -vf scale=128:128 "$preview_name" > /dev/null 2>&1

notify-send -a "🎶 MPD" -i $XDG_CONFIG_HOME/ncmpcpp/previews/RGlzY29ncmFwaHkK.png "Now Playing" "$(mpc --format '%artist% \n%title% - %album%' current)" 
